import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Topo from "@/componentes/Topo";
import Capa from "@/componentes/SecaoCapa";
import Secao_produtos from "@/componentes/SecaoProdutos";
import Secao_sobre from "@/componentes/SecaoSobre";
import Secao_contato from "@/componentes/SecaoContato";
import Rodape from "@/componentes/Rodape";

export default function Home() {
  return (
    <main>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo/>
      <Capa/>
      <Secao_produtos/>
      <Secao_sobre/>
      <Secao_contato/>
      <Rodape/>

    </main>
  );
}
